// Base de dados do Lumiar Palette & Production Engine
// Paletas, fichas de produção e acervo inicial.

export const NICHOS = {
  gestante: {
    nome: "Gestante", resumo: "Oito estilos, do minimalista ao ousado.",
    desc: "O nicho de maior ticket do estúdio. O figurino marca a cintura alta e alonga: tecido fluido, nunca justo na barriga.",
    estilos: [
      { nome: "Minimalista", resumo: "Malha canelada cru, segunda pele, sem acessório.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Areia","#C4B9AB"],["Taupe","#9A8A7B"],["Café","#4A342A"]],
        pecas: ["Vestido de malha canelada cru, segunda pele","Corte de tecido cru de 4 m para drapeado","Pés descalços","Acento: uma aliança e nada mais"],
        tecidos: ["Malha canelada de viscose — caimento pesado, sem transparência","Gaze de algodão — leve, movimento curto"],
        fundo: ["#F4F1EC","Off-white liso, dois níveis mais claro que a roupa"],
        luz: "Uma fonte lateral suave com rebatedor branco. Sombra longa no chão.",
        beleza: "Pele acetinada, boca nude, cabelo liso escovado ou coque baixo.",
        acessorios: "Nenhum, ou uma aliança. Zero metal aparente.",
        cenario: "Estúdio vazio. Banqueta de madeira crua se precisar de apoio.",
        evitar: "estampa, brilho, renda, salto alto, acessório de metal misturado" },
      { nome: "Elegante", resumo: "Vestido longo marinho drapeado, cós elástico.",
        paleta: [["Leite","#F7F2EC"],["Taupe","#9A8A7B"],["Marinho","#1B2540"],["Chumbo","#6E6F71"],["Café","#4A342A"]],
        pecas: ["Vestido longo marinho drapeado de cós elástico","Sandália de tira fina nude","Ouro fosco: argola média e um anel"],
        tecidos: ["Crepe de viscose — estruturado, drapeia sem marcar","Cetim pesado forrado, só no viés"],
        fundo: ["#6E6F71","Cinza chumbo. Marinho pede fundo mais claro que a roupa"],
        luz: "Luz principal a 45° com difusor grande, preenchimento baixo.",
        beleza: "Cabelo alinhado, pele acetinada, olho neutro.",
        acessorios: "Um só metal: ouro fosco. Argola média e um anel.",
        cenario: "Estúdio limpo, cadeira de encosto alto.",
        evitar: "prata junto com ouro, decote profundo, estampa perto do colo" },
      { nome: "Romântico", resumo: "Robe de renda leite sobre top de segunda pele.",
        paleta: [["Leite","#F7F2EC"],["Rosa antigo","#E4BFB6"],["Nude","#D8B8A8"],["Areia","#C4B9AB"],["Cru","#EDE4D6"]],
        pecas: ["Robe de renda branco-leite","Top e short de segunda pele nude","Flores naturais da própria paleta"],
        tecidos: ["Renda chantilly — tom único claro, sempre com contraluz","Tule macio de 4 m para camada solta"],
        fundo: ["#F4F1EC","Off-white com contraluz. Renda precisa de luz atrás"],
        luz: "Contraluz suave com névoa leve, rebatedor frontal fraco.",
        beleza: "Ondas de escova, boca nude-rosada, pele luminosa.",
        acessorios: "Gota de pérola, ouro fino. Flores naturais na mão.",
        cenario: "Cortina de voal, luz de janela, cama branca.",
        evitar: "renda colorida, flor artificial, tiara, brilho de dia" },
      { nome: "Luxo", resumo: "Cetim champanhe transpassado e cauda de tule.",
        paleta: [["Champanhe","#E4CFA8"],["Dourado velho","#B18F4E"],["Ameixa","#4E2A3C"],["Vinho","#6B2230"],["Leite","#F7F2EC"]],
        pecas: ["Vestido de cetim champanhe transpassado","Cauda ampla de tule off-white, 4 m","Sandália dourada de tira fina"],
        tecidos: ["Cetim pesado cortado no viés, sempre forrado","Tule de seda para cauda — 4 m mínimo"],
        fundo: ["#6B2230","Vinho ou chumbo. Cetim claro precisa de fundo escuro"],
        luz: "Luz quente pontual, recorte lateral, fundo em queda de luz.",
        beleza: "Coque baixo com risca, pele luminosa, um só ponto de força.",
        acessorios: "Ouro fosco apenas. Brinco de pedra, clutch rígida.",
        cenario: "Escada, mármore, cortina pesada.",
        evitar: "paetê, lurex, cetim leve, dourado e prata juntos" },
      { nome: "Boho", resumo: "Vestido de algodão cru, trança e externa de fim de tarde.",
        paleta: [["Cru","#EDE4D6"],["Aveia","#D9CDBC"],["Ocre","#C08B3E"],["Camel","#A9855F"],["Oliva","#6E7256"]],
        pecas: ["Vestido de algodão cru de manga ampla","Cinto de couro trançado marrom","Flores secas na mão ou no cabelo"],
        tecidos: ["Algodão rústico — textura visível, movimento lento","Linho lavado, amassado controlado"],
        fundo: ["#C4B9AB","Areia, ou externa de campo no fim de tarde"],
        luz: "Sol baixo por trás, sem rebatedor. Contraluz dourado.",
        beleza: "Trança solta, pele natural, boca neutra.",
        acessorios: "Couro trançado, flores secas. Sem metal brilhante.",
        cenario: "Campo seco, capim alto, tapete no chão.",
        evitar: "franja sintética, penas, estampa étnica grande, brilho" },
      { nome: "Ousado", resumo: "Crepe vinho de manga longa, recorte de luz.",
        paleta: [["Vinho","#6B2230"],["Ameixa","#4E2A3C"],["Preto","#1C1A19"],["Chumbo","#6E6F71"],["Leite","#F7F2EC"]],
        pecas: ["Vestido longo de crepe vinho, manga longa","Corte de tecido café de 4 m para volume","Salto fino preto"],
        tecidos: ["Crepe pesado — sustenta manga e ombro","Musseline café para volume em movimento"],
        fundo: ["#1C1A19","Preto com recorte de luz lateral"],
        luz: "Uma fonte dura lateral, fundo sem luz. Sombra profunda.",
        beleza: "Boca vinho ou olho esfumado, nunca os dois.",
        acessorios: "Um anel forte. Nada no pescoço.",
        cenario: "Estúdio escuro, cadeira preta, chão vazio.",
        evitar: "estampa, brilho, acessório grande, maquiagem dupla no rosto" },
      { nome: "Casal", resumo: "Ela em marinho, ele em popeline lisa da mesma família.",
        paleta: [["Leite","#F7F2EC"],["Azul claro","#A8BDD1"],["Taupe","#9A8A7B"],["Marinho","#1B2540"],["Café","#4A342A"]],
        pecas: ["Vestido longo marinho drapeado","Camisa de popeline lisa azul claro nele","Calça de alfaiataria marinho ou taupe","Cinto e relógio de couro marrom"],
        tecidos: ["Crepe no vestido","Popeline de algodão 100% — sem brilho de poliéster"],
        fundo: ["#F4F1EC","Off-white, ou urbano de dia"],
        luz: "Difusa e ampla, os dois no mesmo plano de foco.",
        beleza: "Natural nos dois. Barba aparada, cabelo alinhado.",
        acessorios: "Couro marrom nele, ouro fosco nela.",
        cenario: "Estúdio claro ou arquitetura urbana.",
        evitar: "roupa igual nos dois, xadrez miúdo, logo, tênis esportivo" },
      { nome: "Com filhos", resumo: "Paleta da mãe repetida em tom vizinho nas crianças.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Aveia","#D9CDBC"],["Areia","#C4B9AB"],["Taupe","#9A8A7B"]],
        pecas: ["Vestido cru de cós elástico na mãe","Camisas e vestidos de algodão liso nas crianças","Todos descalços"],
        tecidos: ["Malha de algodão nas crianças — não amassa em movimento","Gaze de algodão para camada"],
        fundo: ["#C4B9AB","Areia, ou cama branca em casa"],
        luz: "Janela ampla, luz contínua. Criança não espera flash.",
        beleza: "Nenhuma nas crianças. Mãe com pele leve.",
        acessorios: "Nenhum nas crianças.",
        cenario: "Cama branca, tapete cru, chão livre.",
        evitar: "roupa combinando igual, personagem, estampa grande, tênis colorido" }
    ]
  },
  feminino: {
    nome: "Feminino", resumo: "Individual, aniversário e 15 anos.",
    desc: "Aqui o corpo não é o assunto: o rosto é. Decote e gola limpos, e a cor mais forte do look longe da linha do queixo.",
    estilos: [
      { nome: "Individual atemporal", resumo: "Alfaiataria e neutro que não data.",
        paleta: [["Off-white","#F4F1EC"],["Aveia","#D9CDBC"],["Taupe","#9A8A7B"],["Café","#4A342A"],["Preto","#1C1A19"]],
        pecas: ["Conjunto de alfaiataria preto, blazer e calça","Trench aveia apoiado no ombro","Tricô off-white e calça taupe"],
        tecidos: ["Crepe e lã fria — ombro e cintura estruturados","Tricô de viscose, superfície fosca"],
        fundo: ["#F4F1EC","Off-white ou cinza chumbo. Preto pede fundo claro"],
        luz: "Janela lateral ou softbox único. Retrato limpo até o busto.",
        beleza: "Liso escovado, pele acetinada, boca nude-rosada.",
        acessorios: "Ouro fosco, argola média, um anel.",
        cenario: "Estúdio neutro ou urbano de dia.",
        evitar: "estampa no colo, gola de babado, brilho de dia, logo" },
      { nome: "Aniversário", resumo: "Vinho e dourado, ou rosa antigo romântico.",
        paleta: [["Champanhe","#E4CFA8"],["Rosa antigo","#E4BFB6"],["Vinho","#6B2230"],["Ameixa","#4E2A3C"],["Marinho","#1B2540"]],
        pecas: ["Vestido longo de crepe vinho com amarração","Slip de cetim ameixa no viés","Saia de tule rosa e top de renda leite"],
        tecidos: ["Cetim pesado, crepe, tule, renda chantilly","Cetim claro sempre forrado"],
        fundo: ["#6B2230","Vinho ou fundo escuro com luz quente pontual"],
        luz: "Luz quente pontual, recorte. Fundo em queda.",
        beleza: "Ondas de escova ou coque baixo. Um só ponto de força.",
        acessorios: "Brinco de pedra, clutch rígida. Um só metal.",
        cenario: "Estúdio escuro, taça e bolo dentro da paleta.",
        evitar: "paetê integral, lurex, balão metalizado, dois metais no quadro" },
      { nome: "15 anos", resumo: "Vestido de festa mais o look de rua dela.",
        paleta: [["Leite","#F7F2EC"],["Lilás","#B9A8BE"],["Azul claro","#A8BDD1"],["Nude","#D8B8A8"],["Marinho","#1B2540"]],
        pecas: ["Corpete de amarração leite e saia de tule lilás","Saia midi plissada lilás com top leite","Segunda troca: roupa do guarda-roupa dela, lisa"],
        tecidos: ["Tule, organza, plissado, algodão","Nada de cetim pesado nesta idade"],
        fundo: ["#F4F1EC","Off-white claro, ou urbano no fim de tarde"],
        luz: "Luz clara e frontal suave. Nada dramático.",
        beleza: "Cabelo solto natural, pele leve, boca glossada.",
        acessorios: "Brinco pequeno, corrente fina, um anel.",
        cenario: "Estúdio claro, escada, arquitetura urbana.",
        evitar: "branco total, tiara, luva, maquiagem de festa adulta" }
    ]
  },
  newborn: {
    nome: "Newborn", resumo: "Três paletas em camadas, 5 a 12 dias.",
    desc: "O figurino é tecido enrolado, não roupa. Nada no quadro mais claro que a pele do bebê, e cada camada um nível diferente do mesmo neutro.",
    estilos: [
      { nome: "Branco-leite e cru", resumo: "A paleta padrão do nicho e a que mais vende.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Aveia","#D9CDBC"],["Areia","#C4B9AB"],["Taupe","#9A8A7B"]],
        pecas: ["Wrap de malha com elastano leite, 50 cm × 1,80 m","Manta de tricô de ponto fechado cru","Camada de gaze de algodão aveia","Touca de tricô leite"],
        tecidos: ["Malha de algodão com elastano — estica sem apertar","Tricô de ponto fechado — ponto aberto prende dedo"],
        fundo: ["#C4B9AB","Areia. Do mais escuro no fundo ao mais claro no bebê"],
        luz: "Uma fonte lateral única, contínua e quente. Sem flash.",
        beleza: "Nenhuma. Sala a 26–28 °C e ruído branco.",
        acessorios: "Touca em duas ou três fotos, não na sessão toda.",
        cenario: "Pufe de newborn, cesto de vime, banheira de madeira.",
        evitar: "branco ótico, lã que solta fibra, botão nas costas, zíper" },
      { nome: "Terroso quente", resumo: "Para pele morena e quarto amadeirado.",
        paleta: [["Cru","#EDE4D6"],["Nude","#D8B8A8"],["Ocre","#C08B3E"],["Camel","#A9855F"],["Noz","#7A5A44"]],
        pecas: ["Wrap de malha nude no tom da pele","Manta de tricô camel","Cesto de vime ou banheira de madeira"],
        tecidos: ["Malha com elastano nude","Tricô camel de ponto fechado"],
        fundo: ["#7A5A44","Marrom-noz. Luz quente reforça esta paleta"],
        luz: "Luz quente lateral. Luz fria deixa a paleta amarelada.",
        beleza: "Nenhuma.",
        acessorios: "Ursinho de tricô cru em uma foto.",
        cenario: "Banheira de madeira, berço de vime, tapete cru.",
        evitar: "luz fria, pelúcia sintética, cor extra na cena" },
      { nome: "Empoado", resumo: "Quando a família pede rosa ou azul.",
        paleta: [["Leite","#F7F2EC"],["Rosa antigo","#E4BFB6"],["Lilás","#B9A8BE"],["Azul cinza","#A8BDD1"],["Areia","#C4B9AB"]],
        pecas: ["Wrap rosa antigo ou azul acinzentado","Manta leite ou cru embaixo","Tiara fina de tecido leite"],
        tecidos: ["Malha com elastano em tom empoado","Gaze de algodão para camada solta"],
        fundo: ["#C4B9AB","Areia com luz suave frontal"],
        luz: "Suave e frontal. Uma cor empoada por sessão, nunca duas.",
        beleza: "Nenhuma.",
        acessorios: "Tiara fina de tecido. Nunca laço grande.",
        cenario: "Pufe, cesto, flor seca da mesma cor ao lado.",
        evitar: "rosa-bebê, azul-bebê saturado, laço grande, gravata borboleta" }
    ]
  },
  familia: {
    nome: "Família", resumo: "Paleta de três tons, ninguém igual.",
    desc: "Uma paleta de três tons vizinhos distribuída entre todos: ninguém com a mesma peça, ninguém fora da família de cor.",
    estilos: [
      { nome: "Neutro de estúdio", resumo: "Cru, aveia e taupe distribuídos.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Aveia","#D9CDBC"],["Areia","#C4B9AB"],["Taupe","#9A8A7B"]],
        pecas: ["Camisa de popeline off-white nele","Vestido ou tricô cru nela","Camisas e vestidos de algodão liso nas crianças","Todos descalços"],
        tecidos: ["Popeline de algodão, malha, tricô de viscose","Superfície fosca em todos"],
        fundo: ["#F4F1EC","Off-white. O fundo que aceita qualquer roupa clara"],
        luz: "Softbox amplo frontal, todos no mesmo plano.",
        beleza: "Natural. Cabelo alinhado nos adultos.",
        acessorios: "Mínimos. Nenhum nas crianças.",
        cenario: "Estúdio limpo, banqueta e tapete cru.",
        evitar: "roupa idêntica, xadrez miúdo, personagem, tênis colorido" },
      { nome: "Terroso de externa", resumo: "Camel, oliva e cru em campo ou parque.",
        paleta: [["Cru","#EDE4D6"],["Aveia","#D9CDBC"],["Camel","#A9855F"],["Oliva","#6E7256"],["Noz","#7A5A44"]],
        pecas: ["Camisa de linho cru e calça camel","Vestido longo de algodão oliva","Suspensório e boina de tweed nas crianças","Cinto e bota de couro marrom"],
        tecidos: ["Linho lavado, algodão rústico, tweed leve"],
        fundo: ["#6E7256","Verde natural do local, fim de tarde"],
        luz: "Sol baixo por trás, rebatedor branco frontal.",
        beleza: "Natural, cabelo solto.",
        acessorios: "Couro marrom, chapéu de palha.",
        cenario: "Campo, capim alto, tapete no chão.",
        evitar: "preto no meio do verde, branco ótico, estampa grande" },
      { nome: "Inverno escuro", resumo: "Marinho, chumbo e café com tricô.",
        paleta: [["Leite","#F7F2EC"],["Chumbo","#6E6F71"],["Café","#4A342A"],["Marinho","#1B2540"],["Preto","#1C1A19"]],
        pecas: ["Tricôs marinho, chumbo e café distribuídos","Calça de alfaiataria escura em todos","Bota de couro marrom"],
        tecidos: ["Tricô de lã fria, crepe, sarja escura"],
        fundo: ["#6E6F71","Cinza chumbo, ou urbano de inverno"],
        luz: "Luz suave ampla, contraste médio.",
        beleza: "Natural, pele acetinada.",
        acessorios: "Couro marrom. Nada de cachecol estampado.",
        cenario: "Estúdio chumbo, escada urbana.",
        evitar: "todos de preto, xadrez, gola rolê em todo mundo" }
    ]
  }
};
