// Parte 2: nichos restantes, acervo inicial, tecidos técnicos e lista de compras.

export const NICHOS2 = {
  infantil: {
    nome: "Infantil", resumo: "Algodão liso, 2 a 8 anos.",
    desc: "Criança em roupa lisa e confortável fotografa melhor do que criança arrumada. Nada de personagem, nada de sapato novo.",
    estilos: [
      { nome: "Natural de estúdio", resumo: "Algodão cru e cesto de vime.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Aveia","#D9CDBC"],["Areia","#C4B9AB"],["Camel","#A9855F"]],
        pecas: ["Camiseta ou camisa de algodão liso cru","Vestido de algodão cru de cós elástico","Descalço sempre"],
        tecidos: ["Malha de algodão — não amassa em movimento","Algodão rústico no vestido"],
        fundo: ["#C4B9AB","Areia ou off-white, fundo liso"],
        luz: "Luz contínua ampla. Criança não espera flash recarregar.",
        beleza: "Nenhuma. Cabelo do jeito que ela usa.",
        acessorios: "Nenhum. Brinquedo de madeira como apoio.",
        cenario: "Cesto de vime, banqueta, tapete cru.",
        evitar: "personagem, estampa grande, sapato novo, laço de plástico" },
      { nome: "Clássico", resumo: "Suspensório, boina de tweed e vestido liso.",
        paleta: [["Leite","#F7F2EC"],["Aveia","#D9CDBC"],["Camel","#A9855F"],["Café","#4A342A"],["Marinho","#1B2540"]],
        pecas: ["Camisa branca, suspensório e boina de tweed","Vestido liso de algodão com meia-calça","Sapato de couro marrom"],
        tecidos: ["Tweed leve, popeline de algodão, meia-calça de algodão"],
        fundo: ["#7A5A44","Marrom-noz ou parede de madeira"],
        luz: "Luz lateral quente, contraste médio.",
        beleza: "Cabelo penteado, nada mais.",
        acessorios: "Um só detalhe de tweed por look.",
        cenario: "Poltrona, livros, madeira escura.",
        evitar: "gravata borboleta de elástico brilhante, sapato de verniz colorido" },
      { nome: "Smash the cake", resumo: "Um aninho, bolo dentro da paleta.",
        paleta: [["Leite","#F7F2EC"],["Rosa antigo","#E4BFB6"],["Nude","#D8B8A8"],["Aveia","#D9CDBC"],["Camel","#A9855F"]],
        pecas: ["Body ou vestido de algodão liso","Bolo com glacê na mesma paleta da roupa","Toalha e muda de roupa seca à mão"],
        tecidos: ["Malha de algodão lavável — vai sujar"],
        fundo: ["#EDE4D6","Cru. Fundo claro para o bolo não sumir"],
        luz: "Luz ampla e clara, obturador rápido.",
        beleza: "Nenhuma.",
        acessorios: "Nenhum. Coroa e faixa ficam fora.",
        cenario: "Mesa baixa de madeira crua, chão forrado.",
        evitar: "bolo colorido fora da paleta, balão metalizado, faixa de aniversário" }
    ]
  },
  temas: {
    nome: "Temas e minissessões", resumo: "Natal, Páscoa, verão e datas.",
    desc: "Minissessão é volume: uma montagem, várias famílias no mesmo dia. A paleta fecha antes de comprar o cenário.",
    estilos: [
      { nome: "Natal terroso", resumo: "Madeira, vime e tricô cru — sem vermelho-vivo.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Camel","#A9855F"],["Vinho","#6B2230"],["Oliva","#6E7256"]],
        pecas: ["Tricô cru ou camel em todos","Vestido de algodão cru nas crianças","Guirlanda natural, meia de tricô cru"],
        tecidos: ["Tricô de algodão, linho cru, veludo vinho em pouca quantidade"],
        fundo: ["#7A5A44","Marrom-noz com luz quente pontual"],
        luz: "Luz quente pontual simulando lareira, fundo em queda.",
        beleza: "Natural, pele quente.",
        acessorios: "Madeira e vime no lugar do plástico.",
        cenario: "Árvore natural, guirlanda, madeira e vime.",
        evitar: "vermelho-vivo, verde-bandeira, enfeite metalizado, Papai Noel de plástico" },
      { nome: "Natal branco", resumo: "Neutro total, luz alta e árvore desnuda.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Areia","#C4B9AB"],["Prata fosca","#B9BCBE"],["Taupe","#9A8A7B"]],
        pecas: ["Tricô leite em todos, tons vizinhos","Vestido de tule cru nas meninas","Meia de tricô cru"],
        tecidos: ["Tricô leite, tule cru, algodão leve"],
        fundo: ["#F4F1EC","Off-white, luz alta e uniforme"],
        luz: "Luz alta e chapada, pouca sombra. Neve de algodão opcional.",
        beleza: "Pele luminosa, boca nude.",
        acessorios: "Prata fosca, se houver metal. Nunca dourado junto.",
        cenario: "Árvore sem enfeite colorido, luzes quentes fora de foco.",
        evitar: "dourado junto com prata, enfeite vermelho, glitter" },
      { nome: "Páscoa", resumo: "Nude, lilás e cru com palha natural.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Nude","#D8B8A8"],["Lilás","#B9A8BE"],["Aveia","#D9CDBC"]],
        pecas: ["Vestido ou camisa de algodão liso claro","Cesto de palha com ovos em tom empoado","Orelhas de tecido cru, se houver"],
        tecidos: ["Algodão liso, gaze, palha natural"],
        fundo: ["#EDE4D6","Cru claro, luz frontal suave"],
        luz: "Luz frontal suave e clara, primavera.",
        beleza: "Natural, pele fresca.",
        acessorios: "Flores naturais lilás e brancas.",
        cenario: "Cesto de palha, grama, flores de campo.",
        evitar: "ovo colorido saturado, coelho de pelúcia grande, glitter" },
      { nome: "Verão", resumo: "Linho cru e azul acinzentado, fim de tarde.",
        paleta: [["Leite","#F7F2EC"],["Cru","#EDE4D6"],["Areia","#C4B9AB"],["Azul cinza","#A8BDD1"],["Oliva","#6E7256"]],
        pecas: ["Linho cru e camisa azul acinzentada","Vestido leve de algodão claro","Chapéu de palha natural"],
        tecidos: ["Linho lavado, algodão leve, gaze"],
        fundo: ["#C4B9AB","Areia natural do local, sol baixo"],
        luz: "Sol baixo por trás, contraluz dourado.",
        beleza: "Natural, cabelo ao vento.",
        acessorios: "Chapéu de palha. Descalço.",
        cenario: "Praia, campo, fim de tarde.",
        evitar: "estampa tropical, neon, boia colorida, óculos espelhado" }
    ]
  },
  casal: {
    nome: "Casal", resumo: "Urbano, editorial e pré-wedding.",
    desc: "Os dois nunca com a mesma peça. Ela define a paleta, ele entra em um tom vizinho mais escuro.",
    estilos: [
      { nome: "Urbano de dia", resumo: "Alfaiataria neutra em arquitetura.",
        paleta: [["Off-white","#F4F1EC"],["Aveia","#D9CDBC"],["Taupe","#9A8A7B"],["Chumbo","#6E6F71"],["Preto","#1C1A19"]],
        pecas: ["Conjunto de alfaiataria preto nela","Camisa de popeline off-white e calça taupe nele","Trench aveia como terceira peça"],
        tecidos: ["Crepe, lã fria, popeline de algodão"],
        fundo: ["#6E6F71","Concreto e arquitetura, luz de dia difusa"],
        luz: "Luz natural difusa, sombra aberta entre prédios.",
        beleza: "Natural nos dois, cabelo alinhado.",
        acessorios: "Couro marrom nele, ouro fosco nela.",
        cenario: "Concreto, vidro, escada urbana.",
        evitar: "logo, xadrez miúdo, roupa combinando igual, óculos escuro" },
      { nome: "Editorial noturno", resumo: "Vinho e preto com recorte de luz.",
        paleta: [["Leite","#F7F2EC"],["Vinho","#6B2230"],["Ameixa","#4E2A3C"],["Marinho","#1B2540"],["Preto","#1C1A19"]],
        pecas: ["Slip de cetim ameixa ou crepe vinho nela","Camisa preta ou blazer chumbo nele","Salto fino e sapato de couro preto"],
        tecidos: ["Cetim pesado no viés, crepe, lã fria"],
        fundo: ["#1C1A19","Preto com luz lateral dura"],
        luz: "Recorte lateral duro, fundo sem luz.",
        beleza: "Um só ponto de força no rosto dela.",
        acessorios: "Um só metal no quadro.",
        cenario: "Estúdio escuro, corredor com luz pontual.",
        evitar: "brilho sintético, dois metais, maquiagem dupla no rosto" },
      { nome: "Pré-wedding", resumo: "Cauda de tule off-white e terno marinho.",
        paleta: [["Leite","#F7F2EC"],["Champanhe","#E4CFA8"],["Nude","#D8B8A8"],["Taupe","#9A8A7B"],["Marinho","#1B2540"]],
        pecas: ["Vestido de cetim champanhe ou tule off-white","Cauda ampla de 4 m para foto de vento","Terno marinho com gravata de seda lisa"],
        tecidos: ["Tule de seda, cetim pesado forrado, lã fria no terno"],
        fundo: ["#F4F1EC","Off-white com contraluz, ou campo ao fim de tarde"],
        luz: "Contraluz de fim de tarde, rebatedor frontal.",
        beleza: "Ondas alinhadas, pele luminosa.",
        acessorios: "Ouro fosco nos dois, um só metal.",
        cenario: "Campo aberto com vento, ou estúdio claro.",
        evitar: "véu curto de renda rígida, paetê, colete estampado" }
    ]
  },
  corporativo: {
    nome: "Corporativo", resumo: "Retrato, equipe e ambiente.",
    desc: "Retrato de trabalho: enquadramento até o busto, gola limpa e fundo que não disputa. O figurino é o que a pessoa usa no dia a dia, sem amassado.",
    estilos: [
      { nome: "Retrato executivo", resumo: "Blazer escuro e camisa lisa, fundo chumbo.",
        paleta: [["Off-white","#F4F1EC"],["Azul claro","#A8BDD1"],["Chumbo","#6E6F71"],["Marinho","#1B2540"],["Preto","#1C1A19"]],
        pecas: ["Blazer marinho ou chumbo","Camisa de popeline lisa off-white ou azul claro","Gravata de seda lisa, se o setor pedir"],
        tecidos: ["Lã fria no blazer, popeline de algodão na camisa"],
        fundo: ["#6E6F71","Cinza chumbo liso, o padrão de retrato corporativo"],
        luz: "Principal a 45° com softbox, preenchimento suave, luz de recorte no ombro.",
        beleza: "Pele matificada, cabelo alinhado. Pó translúcido obrigatório.",
        acessorios: "Relógio discreto. Sem caneta ou crachá no bolso.",
        cenario: "Fundo liso. Enquadramento até o busto.",
        evitar: "camisa xadrez, listra estreita, logo, brilho de poliéster" },
      { nome: "Equipe", resumo: "Mesma família de cor, peças diferentes.",
        paleta: [["Off-white","#F4F1EC"],["Cru","#EDE4D6"],["Taupe","#9A8A7B"],["Chumbo","#6E6F71"],["Marinho","#1B2540"]],
        pecas: ["Camisa ou tricô liso na mesma família de cor","Blazer opcional, não obrigatório para todos","Calça escura em todos"],
        tecidos: ["Popeline, tricô de viscose, sarja escura"],
        fundo: ["#F4F1EC","Off-white, ou a parede real da empresa se for lisa"],
        luz: "Luz ampla e uniforme, todos no mesmo plano de foco.",
        beleza: "Pó translúcido em todos antes do clique.",
        acessorios: "Mínimos e iguais em nível, não em peça.",
        cenario: "Parede lisa, escada, mesa longa.",
        evitar: "uniforme improvisado, cores do logo no figurino, fila reta" },
      { nome: "Ambiente de trabalho", resumo: "Look real no espaço real.",
        paleta: [["Off-white","#F4F1EC"],["Aveia","#D9CDBC"],["Taupe","#9A8A7B"],["Café","#4A342A"],["Marinho","#1B2540"]],
        pecas: ["Roupa que a pessoa realmente usa, vaporizada","Tricô ou camisa lisa, manga longa","Relógio e cinto de couro marrom"],
        tecidos: ["Tricô de viscose, popeline, sarja"],
        fundo: ["#D9CDBC","O próprio ambiente desfocado, em tom neutro"],
        luz: "Luz do ambiente reforçada por uma fonte suave. Abertura aberta.",
        beleza: "Mãos limpas: aparecem em close.",
        acessorios: "Couro marrom, relógio.",
        cenario: "Bancada, oficina, ateliê. Mesa organizada.",
        evitar: "mesa poluída, monitor ligado com marca, cadeira colorida" }
    ]
  }
};

// Acervo inicial — peças da Lista de compras já cadastradas.
export const ACERVO = [
  { id:"a01", tipo:"Fundo", nome:"Fundo off-white", codigo:"FD-01", cor:"Off-white", hex:"#F4F1EC", tecido:"Algodão fosco", metragem:"2,70 m", largura:"2,70 m", tamanho:"—", estado:"Novo", local:"Suporte A", qtd:1, nichos:["gestante","feminino","familia","infantil","newborn","casal","corporativo","temas"] },
  { id:"a02", tipo:"Fundo", nome:"Fundo areia", codigo:"FD-02", cor:"Areia", hex:"#C4B9AB", tecido:"Algodão fosco", metragem:"2,70 m", largura:"2,70 m", tamanho:"—", estado:"Novo", local:"Suporte A", qtd:1, nichos:["newborn","infantil","temas","familia"] },
  { id:"a03", tipo:"Fundo", nome:"Fundo cinza chumbo", codigo:"FD-03", cor:"Chumbo", hex:"#6E6F71", tecido:"Algodão fosco", metragem:"2,70 m", largura:"2,70 m", tamanho:"—", estado:"Novo", local:"Suporte B", qtd:1, nichos:["corporativo","casal","feminino","gestante"] },
  { id:"a04", tipo:"Vestido", nome:"Vestido longo marinho drapeado", codigo:"VS-01", cor:"Marinho", hex:"#1B2540", tecido:"Crepe de viscose", metragem:"—", largura:"—", tamanho:"P/M/G — cós elástico", estado:"Bom", local:"Arara 1", qtd:1, nichos:["gestante","feminino","casal","familia"] },
  { id:"a05", tipo:"Vestido", nome:"Vestido de cetim champanhe", codigo:"VS-02", cor:"Champanhe", hex:"#E4CFA8", tecido:"Cetim pesado forrado", metragem:"—", largura:"—", tamanho:"M/G — transpassado", estado:"Bom", local:"Arara 1", qtd:1, nichos:["gestante","feminino","casal"] },
  { id:"a06", tipo:"Vestido", nome:"Vestido de crepe vinho", codigo:"VS-03", cor:"Vinho", hex:"#6B2230", tecido:"Crepe pesado", metragem:"—", largura:"—", tamanho:"P/M/G — amarração", estado:"Novo", local:"Arara 1", qtd:1, nichos:["feminino","casal","gestante"] },
  { id:"a07", tipo:"Vestido", nome:"Vestido de malha canelada cru", codigo:"VS-04", cor:"Cru", hex:"#EDE4D6", tecido:"Malha canelada de viscose", metragem:"—", largura:"—", tamanho:"P/M/G", estado:"Bom", local:"Arara 1", qtd:1, nichos:["gestante","feminino"] },
  { id:"a08", tipo:"Vestido", nome:"Robe de renda branco-leite", codigo:"VS-05", cor:"Leite", hex:"#F7F2EC", tecido:"Renda chantilly", metragem:"—", largura:"—", tamanho:"Único", estado:"Bom", local:"Arara 1", qtd:1, nichos:["gestante","feminino"] },
  { id:"a09", tipo:"Tecido", nome:"Corte de tecido cru", codigo:"TC-01", cor:"Cru", hex:"#EDE4D6", tecido:"Musseline de algodão", metragem:"4 m", largura:"1,50 m", tamanho:"—", estado:"Novo", local:"Gaveta 2", qtd:1, nichos:["gestante","newborn","temas","casal"] },
  { id:"a10", tipo:"Tecido", nome:"Corte de tecido areia", codigo:"TC-02", cor:"Areia", hex:"#C4B9AB", tecido:"Musseline de algodão", metragem:"4 m", largura:"1,50 m", tamanho:"—", estado:"Novo", local:"Gaveta 2", qtd:1, nichos:["gestante","newborn","temas","familia"] },
  { id:"a11", tipo:"Tecido", nome:"Corte de tecido marrom café", codigo:"TC-03", cor:"Café", hex:"#4A342A", tecido:"Musseline de algodão", metragem:"4 m", largura:"1,50 m", tamanho:"—", estado:"Novo", local:"Gaveta 2", qtd:1, nichos:["gestante","casal","familia"] },
  { id:"a12", tipo:"Tecido", nome:"Wrap de malha leite", codigo:"TC-04", cor:"Leite", hex:"#F7F2EC", tecido:"Malha de algodão com elastano", metragem:"1,80 m", largura:"50 cm", tamanho:"—", estado:"Novo", local:"Gaveta 1", qtd:2, nichos:["newborn"] },
  { id:"a13", tipo:"Tecido", nome:"Wrap de malha nude", codigo:"TC-05", cor:"Nude", hex:"#D8B8A8", tecido:"Malha de algodão com elastano", metragem:"1,80 m", largura:"50 cm", tamanho:"—", estado:"Novo", local:"Gaveta 1", qtd:2, nichos:["newborn"] },
  { id:"a14", tipo:"Tecido", nome:"Manta de tricô cru", codigo:"TC-06", cor:"Cru", hex:"#EDE4D6", tecido:"Tricô de algodão de ponto fechado", metragem:"—", largura:"—", tamanho:"80 × 80 cm", estado:"Bom", local:"Gaveta 1", qtd:2, nichos:["newborn","infantil","temas","familia"] },
  { id:"a15", tipo:"Figurino masculino", nome:"Camisa de popeline off-white", codigo:"CM-01", cor:"Off-white", hex:"#F4F1EC", tecido:"Popeline de algodão", metragem:"—", largura:"—", tamanho:"M / G / GG", estado:"Novo", local:"Arara 2", qtd:3, nichos:["casal","familia","corporativo","gestante"] },
  { id:"a16", tipo:"Figurino masculino", nome:"Camisa de popeline azul claro", codigo:"CM-02", cor:"Azul claro", hex:"#A8BDD1", tecido:"Popeline de algodão", metragem:"—", largura:"—", tamanho:"M / G / GG", estado:"Novo", local:"Arara 2", qtd:3, nichos:["casal","familia","corporativo"] },
  { id:"a17", tipo:"Figurino masculino", nome:"Blazer marinho", codigo:"BL-01", cor:"Marinho", hex:"#1B2540", tecido:"Lã fria", metragem:"—", largura:"—", tamanho:"M / G", estado:"Bom", local:"Arara 2", qtd:2, nichos:["corporativo","casal","familia","feminino"] },
  { id:"a18", tipo:"Figurino masculino", nome:"Blazer chumbo", codigo:"BL-02", cor:"Chumbo", hex:"#6E6F71", tecido:"Lã fria", metragem:"—", largura:"—", tamanho:"M / G", estado:"Bom", local:"Arara 2", qtd:2, nichos:["corporativo","casal","familia"] },
  { id:"a19", tipo:"Cenário", nome:"Cesto de vime", codigo:"CN-01", cor:"Palha", hex:"#C08B3E", tecido:"Vime natural", metragem:"—", largura:"—", tamanho:"60 cm", estado:"Bom", local:"Prateleira 1", qtd:1, nichos:["newborn","infantil","temas","familia"] },
  { id:"a20", tipo:"Cenário", nome:"Banqueta de madeira crua", codigo:"CN-02", cor:"Noz", hex:"#7A5A44", tecido:"Madeira", metragem:"—", largura:"—", tamanho:"45 cm", estado:"Bom", local:"Prateleira 1", qtd:2, nichos:["gestante","infantil","familia","feminino"] },
  { id:"a21", tipo:"Cenário", nome:"Tapete cru", codigo:"CN-03", cor:"Cru", hex:"#EDE4D6", tecido:"Algodão trançado", metragem:"—", largura:"—", tamanho:"1,4 × 2 m", estado:"Bom", local:"Prateleira 2", qtd:1, nichos:["newborn","infantil","familia","temas"] },
  { id:"a22", tipo:"Acessório", nome:"Kit de ouro fosco", codigo:"AC-01", cor:"Dourado velho", hex:"#B18F4E", tecido:"Metal banhado", metragem:"—", largura:"—", tamanho:"—", estado:"Bom", local:"Gaveta 3", qtd:1, nichos:["gestante","feminino","casal","corporativo"] },
  { id:"a23", tipo:"Acessório", nome:"Cinto e relógio de couro marrom", codigo:"AC-02", cor:"Café", hex:"#4A342A", tecido:"Couro", metragem:"—", largura:"—", tamanho:"—", estado:"Bom", local:"Gaveta 3", qtd:1, nichos:["casal","familia","corporativo"] },
  { id:"a24", tipo:"Acessório", nome:"Kit de retoque e vaporizador", codigo:"AC-03", cor:"—", hex:"#9A8A7B", tecido:"—", metragem:"—", largura:"—", tamanho:"—", estado:"Novo", local:"Bancada", qtd:1, nichos:["gestante","feminino","familia","infantil","newborn","casal","corporativo","temas"] }
];

export const TIPOS = ["Vestido","Tecido","Figurino masculino","Figurino infantil","Acessório","Cenário","Fundo"];
export const ESTADOS = ["Novo","Bom","Usado","Reparar"];

// Tecidos: comportamento fotográfico e metragem de referência.
export const TECIDOS = [
  { nome:"Tule", peso:"Muito leve", transp:"Alta", caimento:"Volume aberto", luz:"Difunde e brilha em contraluz", uso:"Cauda, camada, saia ampla", metragem:"4 m mínimo para cauda" },
  { nome:"Musseline", peso:"Leve", transp:"Média", caimento:"Fluido com movimento longo", luz:"Difusa, sem brilho", uso:"Tecido esvoaçante, drapeado", metragem:"4 a 6 m para esvoaçante" },
  { nome:"Chiffon", peso:"Leve", transp:"Média", caimento:"Fluido, cai reto", luz:"Fosca", uso:"Sobreposição, manga ampla", metragem:"3 a 5 m" },
  { nome:"Organza", peso:"Leve", transp:"Média", caimento:"Estruturado, guarda forma", luz:"Leve brilho", uso:"Volume que sustenta", metragem:"3 a 4 m" },
  { nome:"Crepe", peso:"Médio", transp:"Nenhuma", caimento:"Drapeia sem marcar", luz:"Totalmente fosca", uso:"Vestido longo, alfaiataria", metragem:"3 a 4 m para vestido" },
  { nome:"Cetim pesado", peso:"Médio-alto", transp:"Nenhuma", caimento:"Escorrido no viés", luz:"Brilho controlado", uso:"Slip, vestido de luxo", metragem:"3,5 a 4,5 m no viés" },
  { nome:"Veludo", peso:"Alto", transp:"Nenhuma", caimento:"Pesado, cai reto", luz:"Absorve luz, profundidade", uso:"Inverno, Natal, editorial", metragem:"3 a 4 m" },
  { nome:"Linho", peso:"Médio", transp:"Baixa", caimento:"Rígido, amassa", luz:"Textura visível", uso:"Externa, boho, verão", metragem:"2,5 a 3,5 m" },
  { nome:"Malha com elastano", peso:"Leve", transp:"Nenhuma", caimento:"Elástico, envolve", luz:"Fosca", uso:"Wrap de newborn, segunda pele", metragem:"50 cm × 1,80 m por wrap" },
  { nome:"Renda chantilly", peso:"Leve", transp:"Alta", caimento:"Macio, acompanha o corpo", luz:"Precisa de contraluz", uso:"Robe, top, sobreposição", metragem:"2 a 3 m" },
  { nome:"Gaze de algodão", peso:"Muito leve", transp:"Média", caimento:"Solto, amassado natural", luz:"Fosca e suave", uso:"Camada de newborn, verão", metragem:"2 a 3 m" },
  { nome:"Tricô de ponto fechado", peso:"Médio", transp:"Nenhuma", caimento:"Denso", luz:"Textura suave", uso:"Manta, touca, inverno", metragem:"80 × 80 cm por manta" }
];

export const COMPRAS_SEED = [
  { id:"c01", item:"Wrap de malha rosa antigo", qtd:"1", esp:"50 cm × 1,80 m, algodão com elastano", hex:"#E4BFB6", prio:"alta", fim:"Newborn empoado" },
  { id:"c02", item:"Wrap de malha azul acinzentado", qtd:"1", esp:"50 cm × 1,80 m, algodão com elastano", hex:"#A8BDD1", prio:"alta", fim:"Newborn empoado" },
  { id:"c03", item:"Manta de tricô camel", qtd:"2", esp:"80 × 80 cm, ponto fechado", hex:"#A9855F", prio:"alta", fim:"Newborn terroso" },
  { id:"c04", item:"Conjunto de alfaiataria preto", qtd:"2", esp:"Blazer e calça, M e G", hex:"#1C1A19", prio:"media", fim:"Feminino e corporativo" },
  { id:"c05", item:"Trench aveia", qtd:"1", esp:"Comprimento midi, cós com cinto", hex:"#D9CDBC", prio:"media", fim:"Individual e externa" },
  { id:"c06", item:"Saia de tule lilás e corpete leite", qtd:"1", esp:"Corpete de amarração nas costas", hex:"#B9A8BE", prio:"media", fim:"15 anos" },
  { id:"c07", item:"Fundo marrom-noz", qtd:"1", esp:"2,70 m, tecido fosco", hex:"#7A5A44", prio:"media", fim:"Newborn terroso e temas" },
  { id:"c08", item:"Cauda de tule off-white", qtd:"1", esp:"4 m, tule de seda", hex:"#F4F1EC", prio:"baixa", fim:"Gestante luxo e pré-wedding" },
  { id:"c09", item:"Fundo texturizado pintado à mão", qtd:"1", esp:"2,70 m, cinza-esverdeado", hex:"#6E7256", prio:"baixa", fim:"Todos os nichos de estúdio" }
];
